<form method="post" action="index.php">
    
    <fieldset>
        <label for="login">Login</label>
        <input type="email" name="login" id="login" />
    </fieldset>
    
    <fieldset>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" />
    </fieldset>
    
    <fieldset>
        <label for="formName">Form Name</label>
        <input type="hidden" name="formName" id="formName" />
    </fieldset>
    
</form>
